//test exception 11

int f(int* p)
{
  *p;
  return f(p);
}

int main()
{
  return f(alloc(int));
}
