//test exception
// oh god the stack explod-fffffff

int f(int n)
{
  n = n + n;
  return f(n) + f(n);
}

int main()
{
  return f(1);
}
