//test exception 11

struct s
{
int* p1;
int* p2;
int* p3;
int* p4;
int* p5;
int* p6;
int* p7;
int* p8;
int* p9;
int* p10;
int* p11;
int* p12;
int* p13;
int* p14;
int* p15;
int* p16;
int* p17;
int* p18;
int* p19;
int* p20;
int* p21;
int* p22;
int* p23;
int* p24;
int* p25;
int* p26;
int* p27;
int* p28;
int* p29;
int* p30;
int* p31;
int* p32;
};

struct t
{
  struct s s1;
  struct s s2;
  struct s s3;
  struct s s4;
  struct s s5;
  struct s s6;
  struct s s7;
  struct s s8;
  struct s s9;
  struct s s10;
  struct s s11;
  struct s s12;
  struct s s13;
  struct s s14;
  struct s s15;
  struct s s16;
};

struct r
{
  struct t t1;
  struct t t2;
  struct t t3;
  struct t t4;
  struct t t5;
  struct t t6;
  struct t t7;
  struct t t8;
};

int main()
{
  struct r* x = NULL;
  x->t8.s16.p32 = alloc(int);
  *(x->t8.s16.p32) = 42;
  return *(x->t8.s16.p32);
}
